### ISSUE TITLE
Add ability for individual input switches instead of analog line

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#11]
Add the option in code to not use the analog switch input AD0 line and use dedicated digital I/O lines (selectable lines in code like for the activity indicator lines) for individual switches instead? This would come in handy for people who want to make custom projects and avoid dealing with possible resistor tolerance issues with using analog. Each line pulled low and detected with logical high with switch closure.

**Comment by Kalidomra** [comment]
How many buttons are you thinking? Why not use the internal pull up resistors on the Mega pins? That would mean switch activation on low. No extra resistors.

**Comment by JohnLundy** [comment]
That's even better. The ADE is designed to work with the five switches on the LCD/Button shield. I'd say the ability for all five makes the most sense, even though I don't use the dedicated unmount switch in favor of the mount/unmount dual purpose switch.

**Comment by Kalidomra** [comment]
Do you know how the ADE reacts if there is nothing attached to the AD0? Do I have to disable it in code or can I leave both analog and digital buttons functional regardless of whether they are installed or not.

**Comment by JohnLundy** [comment]
I don't know the exact answer to that without real world testing. With that said, the AD0 line requires a 2k pull up for normal operation as part of the switch voltage divider even without any switch closures according to the schematic. I see no reason the system couldn't have both input methods, I just wouldn't leave the AD0 line floating without a 2k pull up to play it safe.

**Comment by Kalidomra** [comment]
I will add the ability to disable the analog buttons in the configuration section.

**Comment by Kalidomra** [comment]
Complete in v0.4
