### ISSUE TITLE
Analog buttons still enabled during boot when using digital buttons

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#14]
Analog buttons still enabled during boot when using digital buttons and intermittently causing unit to falsely boot to config mode on power up. This is an issue only when designs are based around using digital buttons.  Need to add check if ‘EnableAnalogButtons = false’ variable is set to ignore analog buttons during boot when checking if the select key is held down to enable config mode on boot up.

**Comment by Kalidomra** [comment]
Fixed in beta v0.6
