### ISSUE TITLE
Button scan time changes for digital buttons vs. analog buttons

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#15]
Add the ability to change button scan times based on both digital and analog button settings. Maybe have this ability tied to the ‘EnableAnalogButtons = false/true’ variable adjustment.

Analog buttons seem to work best with a setting of ButtonDelay >= 150 and digital buttons seem to work best with a setting of ButtonDelay >= 120.

**Comment by Kalidomra** [comment]
Added to beta v0.6
