### ISSUE TITLE
Boot disk image is case sensitive

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#18]
For the boot image to automatically boot it has to be all lowercase in order to work, including the extension. Add the ability to make it not case sensitive to make it less confusing.

**Comment by Kalidomra** [comment]
The boot disk filename is definable in the variables at the top of the main Arduino file. In order to make this more user friendly, the defined filename and the filename read from the SD card will need to be converted to lower case and then compared. This should be simple to implement.

**Comment by Kalidomra** [comment]
Fixed in v0.70.
