### ISSUE TITLE
Make mount key dual purpose to mount and unmount files

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#2]
The ability to use the mount key also as the unmount key will reduce keys required and simplify things. Same functionality as the VDD.

**Comment by Kalidomra** [comment]
Can you clarify how this works? Right now if you select the mount key, it unmounts and then mounts the currently selected file on the bottom line.

You want to push the key twice to select a new file? Once to unmount and again to mount?

**Comment by JohnLundy** [comment]
Correct, push twice to select a new file. This gives the option of having nothing mounted without using the left button. Everyone is familiar with this method from using the VDD. If this ever becomes a product or custom shield made, it will require less parts or possibly free up a button for future options.

**Comment by Kalidomra** [comment]
Done.
