### ISSUE TITLE
Setting ‘const unsigned int namelength =’ less than 71 will lock up the ADE.

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#21]
Setting ‘const unsigned int namelength =’ to less than 41 locks the ADE up on boot. Setting it between 41 and 71 will lock the ADE when scrolling through files. Higher the setting will require more scrolling to lock up the ADE. This appears to be a carryover from v0.6 as well.

**Comment by Kalidomra** [comment]
Fixed in v0.80
