### ISSUE TITLE
When using an IDEboot PROM the boot timing is altered and changes the TimeSinceReset value causing issues with ADE compatibility

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#22]
When using an IDEboot PROM in expansion slot 2 the boot timing is altered and changes the TimeSinceReset value causing issues with ADE compatibility. It has been found that it is required to add an additional lower range for compatibility. Tests have show a range of 15 – 23 is required.

 if (((TimeSinceReset <= 175) && (TimeSinceReset >= 153)) || ((TimeSinceReset <= 23) && (TimeSinceReset >= 15))){ // Lower range is needed for IDEboot PROM compatibility

**Comment by Kalidomra** [comment]
Fixed in v0.80
