### ISSUE TITLE
SD Command issues mounting D3 and also throwing errors in the terminal with v0.73

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#23]
SD Command issues mounting D3 and also throwing errors in the terminal with v0.73. It has been found that the buffer needs to be zeroed out first to correct this issue.  

Replace:
LoadedBlock[devicenumber-4] = 0xFFFFFFFF;

With:
BlockBuffer[devicenumber-4][0] = 0xB0 + devicenumber; // Need to zero out the buffer
BlockBuffer[devicenumber-4][1] = 0x04;   
BlockBuffer[devicenumber-4][2] = 0x00;

**Comment by Kalidomra** [comment]
Fixed in v0.80
