### ISSUE TITLE
Read Errors on some Clone Arduino Megas

### ISSUE THREAD

**Issue by Kalidomra** [Kalidomra/AdamNet-Drive-Emulator#24]
Some cheaper Arduino clones use poor quality resonators. This can cause read errors on AdamNet, due to the bit bang timing being off. The Motorola 6801 that is used in the Adam is able to tolerate up to 3.5% difference in serial communication speed.

**Comment by plasticuser** [comment]
I should be ok with a +/- 2--ppm oscillator on my custom Pro board?

**Comment by Kalidomra** [comment]
Generally an oscillator is the preferred method. They are very accurate. 2 ppm is equal to 15999968 hz - 16000032 hz. The issue is with the low quality resonators that some mega clones use. These appear to be outside of the normal tolerances of a name brand resonator. I have measured some at 15850700 hz.

**Comment by plasticuser** [comment]
2--ppm should be 200ppm, sorry.

I'm developing a single board ADE interface that could support two SD cards, ADAMNet pass-thru, and if you'll support it a more satisfying OLED or mini-TFT display. I'm also going to make it VERY small. My main objective is to lower the price so it is more accessible.

I would love to pick your brains about some smaller technical matters, eg: power, and the notion of forking your ADAMNet stack for a video adapter I've designed. dave@nonstickglue.com

**Comment by Kalidomra** [comment]
200ppm is more than accurate enough. I have modified the timings to tolerate the worst mega clone that I have. I am currently testing this. It will be released soon.

If you want to add a feature to the ADE, submit an issue as an improvement. Or you can create your own fork.

**Comment by plasticuser** [comment]
I'd prefer to keep everything unified - forks muddy the waters too much. People need a consistent experience. I'll post a couple of thoughts...

**Comment by Kalidomra** [comment]
Fixed in v0.82
