### ISSUE TITLE
Request OLED or TFT display support...

### ISSUE THREAD

**Issue by plasticuser** [Kalidomra/AdamNet-Drive-Emulator#26]
It would be nice to move beyond 1602 displays. Besides not being very clear, they crop off a lot of the file names. A modest OLED display based around a common chipset would be easy to support.

The killer feature is being able to have three lines of clear, high resolution text, so you can see the selected file, the file above and the file below as you scroll through the list. I think this would greatly improve usability.

**Comment by Kalidomra** [comment]
Please specify the OLED you are thinking of using.

**Comment by plasticuser** [comment]
I was thinking an I2C 0.96" 128x64 unit using the SSD1306 driver. This doesn't interfere with your current use of SPI. They are available in white, blue, or yellow top 1/4 and blue bottom 3/4, There are many brands to choose from. SSD1306 also supports a range of color TFT displays, and other OLED displays of 128x32 size, though those are a bit small for this.

**Comment by plasticuser** [comment]
I have developed this idea further, and this feature has become quite essential to my plans. I intend to add a remote control with a custom matrix keypad - mostly because having a custom remote matrix made and using an OLED display is a cheaper and more elegant solution than buying expensive 1602 displays on button entry PCBs.

Anything which only uses an IR link will work natively with your code without changes, introduce mechanical reliability, and increase mounting options to include internal mounting with only the SD slot and a sensor showing.

It will allow me to lower the retail cost of the ADE by another $10-15, while improving mounting options and usability in almost every way. It will also allow people to buy standard arduino accessory parts that are still cheaper than the 1602 input shields. It doesn't limit accessibility at all.

**Comment by Kalidomra** [comment]
What about the ADE in it's current form is not "mechanically reliable"?
Why would having the ADE functional with a remote control be desired? Will the keyboard and joysticks also be remote? What about the need to reset the Adam?

**Comment by plasticuser** [comment]
Stacks of boards are for prototyping. It's nice that they're available. But to compensate for the fact they're multiple boards held together with jumper wire and push fit contacts, people are charging almost $100 for a box to put it in. One of your stated goals was to make it affordable and accessible to everyone. So, I was simple "productizing" your ADE board. Every request has been an effort to improve the product this code runs on. I do have the ability to produce a single board that can do everything this does for about the same cost as buying all the parts separately - as many have done.

I'm not knocking their experience - I am only reacting to my own observations of my and others' use.

The remote functionality is to allow the ADE to be embedded behind a grille or in a slot. It would allow more room for a larger OLED from the same driver family. The remote would have a custom made front laminate, and would match the Adam perfectly. It would do debounce for you in the remote.

I can't see any benefit in the keyboard or joysticks being remote. The keyboard's an ADAMnet device, and just plugs in right there.

At the end of the day, the LCD/input shield is the weakest and most mechanically vulnerable part of the ADE. It forces a certain chunkiness on the design, and makes it less convenient to embed. It's also the most expensive component. OLED displays are 1/4-1/5 the price. Keyes remotes are 1/4 the price. It just gives people more options to build different implementations. With the SD shield firmly mounted in the 'duino I pressed buttons and the vibration was causing intermittent connection to the SD card, which was problematic.

I'm looking at forking the code, _not to duplicate your work/ADE_ but to use the ADAMnet stack you've developed to allow other options like ADAMnet<>PS/2 adapter as keyboards are in short supply, and an ADAMnet floppy controller, because why not? :D
