### ISSUE TITLE
Add support for 2nd SD slot

### ISSUE THREAD

**Issue by plasticuser** [Kalidomra/AdamNet-Drive-Emulator#28]
It might be nice (and easy) to add support for a second SD card. This might be implemented with a separate SPI port, or shared SPI port and second select line.

It would make copying SD cards much easier without a PC. It would just require a second SD shield.

**Comment by plasticuser** [comment]
![Screen Shot 2020-02-12 at 2 04 54 PM](https://user-images.githubusercontent.com/6180686/74372705-b5e4d380-4da0-11ea-95ba-3856a84184d1.png)
This is what I had in mind. Dual SD cards with screen above them in front of case, plus a backplane of four further expansion slots for future expansion. RJ12 pass-thru. Adam serial would be internally buffered. Minimal ATmega2560 system plus update serial port made directly on board.

**Comment by Kalidomra** [comment]
What is the use case for this? I am unable to see why we would need to copy SD cards on the ADE. A PC or a Mac is better suited for this task.

**Comment by plasticuser** [comment]
One use case is that sometimes a user might want two disk images open, with access to both simultaneously without button pressing. One might contain program, the other data. It makes more sense to have two devices supported by one ATmega than having two separate ADE boards, one configured to each disk position. On John Lundy's product there is an option to select drive 0 or 1.

It is true that doing back-ups is easier on a PC, but it would be more convenient for some to do it on the Adam.

I would ideally like to add a little on-board DIP switch that allows the user to select 0, 1, 2, for the left slot and the right slot be left slot +1. If you decide not to provide this functionality in firmware, I'd have to use two ATmegas and increase the cost on the dual slot boards by about $20. I'd prefer to charge every user $20 less and have it implemented in software.

The main programming task in this is selecting for the display and input to be connected clearly to slot 1 or slot 2. This is a part of why I made the feature request to support OLED displays. More characters, more lines, and higher readability.

**Comment by Kalidomra** [comment]
It is not possible to have 2 disk images associated with an Adam drive simultaneously. The ADE (and all variants) already support 4 ADAM drives, with one SD card.  I'm confused by what you are talking about "drive 0 and 1" The Adam uses 4 device numbers for disk drives (Device 4, 5, 6 and 7). These are called drives 1-4 on the ADE.

**Comment by plasticuser** [comment]
I am maybe using improper terminology.

Devices 4 and 5. (or 5/6, or 6/7)

The ATmega can listen for requests and direct a request for device 4 to slot 1's SD, and for device 5 to slot 2's SD. Two drives could be mounted simultaneously, implemented through a single ATmega.

In a couple of months, when China gets back on its feet, I'll be releasing a LARGE memory expansion for the Adam - more than anyone might ever want to use. 2MB will be standard, with 4/8/12MB shields offering a total of 14MB max. I'll then be releasing a 2MB video card once drivers are a little more developed, rounding out the 16MB max address range through paging. This will open up a lot of new options for the Adam for a certain subset of users. Being able to quickly load and save more than 258K is an important feature, and one that realistically only ADE supports in any meaningful sense.

PS: If microcontroller SRAM is an issue, I have retargeted the code to the AT91SAM3X8E (Due) device. Just because it compiles without error doesn't mean it works, though, but I could as easily design a board around that device if it suits extending functionality. It's a much more capable device. 96K SRAM, 84MHz.

PPS: it is a goal to use your ADAMnet stack to implement parallel, floppy (WD1772), PS/2 and other ports, to go on the backplane. While lowering prices/costs to make this all accessible to a lot more people.

**Comment by plasticuser** [comment]
Re-rephrase. 4 logical drives, two physical SD cards, Be able to map either SD to any available logical drive(s).

There, that's more concise.

Sorry :)

**Comment by Kalidomra** [comment]
You do not need 2 SD cards to do this. This will add complexity that is not required.

**Comment by plasticuser** [comment]
Just to be certain, ADE as it stands supports mounting four logical devices at once to four logical drives off one SD card?

**Comment by Kalidomra** [comment]
Yup. You can even mount the same image to all 4 drives. It will only open the disk image file when it needs to read or write a block and then it will close it.
Do you have an ADE?

**Comment by plasticuser** [comment]
Yes. Self-built. Only been using it a few days though, to have enough awareness to make it into a single board device. I'm just trying to make it available to Joe Blow at a lower price point than ANN, in a highly integrated package.

Your point on multiple logical devices open weakens much of my request, and leaves coding only to be able to duplicate SDs in system. I see your POV much better now. Thank you.

I will close the request.
