### ISSUE TITLE
R/W activity LED

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#3]
Would it be nice to have an activity LED flash when drives are reading or writing. Large loads keep you wondering if anything is happening.

**Comment by Kalidomra** [comment]
Should be there. The default is the LED on the Mega, that happens to get covered up by the keypad. You can easily add an external LED with a resistor. Default is Pin 13.

**Comment by JohnLundy** [comment]
Yep, I didn't notice it under the LCD/Button shield. I added an LED to the shield to make it viewable.
