### ISSUE TITLE
Add support for sketch updating by file on SD card?

### ISSUE THREAD

**Issue by plasticuser** [Kalidomra/AdamNet-Drive-Emulator#30]
It would be nice if users with an existing install of ADE could copy an update onto their SD card, and on start-up the ATmega could check the SD card for an update and import it then reset if one is present. This would allow a lot of users not comfortable with using the Arduino IDE to more easily keep their systems current.

This is also very easy to implement.

**Comment by Kalidomra** [comment]
In my research, this requires a different boot loader. Do you have a method to do this without modifying the boot loader?

**Comment by plasticuser** [comment]
Ah, a wrinkle!

I'm sorry, boot loaders and that level of usage isn't my area of expertise, so I honestly don't know. It was just a thought that might make people's upgrades a bit easier. If it's too complex or increases the footprint too much, it becomes an unrealistic option.

I'll keep googling around and see if there is an alternate way to do it without changing the bootloader.

(Sorry, I'm 90% a hardware guy)
