### ISSUE TITLE
Capacitive touch

### ISSUE THREAD

**Issue by plasticuser** [Kalidomra/AdamNet-Drive-Emulator#31]
It looks like at some point you shifted from capacitive touch to tactile buttons. I was just wondering if this was for a technical reason, or because of the convenience of the tactile buttons included on many LCD shields?

I'm considering using capacitive touch as a way of lowering costs and reducing moving parts, if the OLED option materializes - and maybe even if it doesn't.

This also lets me create a generic LCD shield with capacitive touch that would look really nice for use on standard ATmega boards too.

(I've been waiting for boards for *ages* but some prototype boards just came in so I am back on the case!)

**Comment by Kalidomra** [comment]
The ADE was created with the 1602 LCD Keypad Shield. So, no capacitive touch buttons. Later I added the individual digital buttons as an option.
