### ISSUE TITLE
Bug that allows same file to be mounted to multiple drives

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#4]
Bug that allows same file to be mounted to multiple drives

**Comment by Kalidomra** [comment]
This is not a bug. It is part of the current implementation. Because of the serial nature of AdamNet the same file can be accessed by multiple drives. Each time a block of 1k data is written, the file is opened and closed.

**Comment by JohnLundy** [comment]
Gotcha, thanks for clearing that up. It's kind of hard to wrap your head around it at first.
