### ISSUE TITLE
Blank screen on boot if no SD card is detected

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#5]
Blank screen on boot if no SD card is detected. Maybe add error reading SD card message to reduce confusion

**Comment by Kalidomra** [comment]
I am only able to repeat this action if the SD card is removed while the Mega is powered up, and then the Adam is reset.  Any time the SD card is removed and reinserted, the user should reset the Mega. That is the only way for the Mega to know the card has changed and to poll for new files. I could add a bunch of checks to see if the card has been removed or not, but I would consider this a low priority.

If the Mega is powered up or reset with no card, I have added an error to the LCD.

**Comment by JohnLundy** [comment]
Yes, I was referring to powering it up without an SD card causing a blank screen. I have found that people use cheap extenders that eventually wear and will cause confusion when the issue is a broken connection within the extender itself. Maybe an "Error reading SD card - check connections". Something along those lines.

**Comment by Kalidomra** [comment]
Added to v0.3
