### ISSUE TITLE
Read error during boot of ADAMCalc

### ISSUE THREAD

**Issue by JohnLundy** [Kalidomra/AdamNet-Drive-Emulator#6]
Read error during boot of ADAMCalc. Was not an issue with first beta. Reloaded original beta and confirmed it does load fine on two separate ADAM consoles. Something changed?

**Comment by JohnLundy** [comment]
I have now verified the same behavior with all three of my complete ADAM setups.

**Comment by Kalidomra** [comment]
I have isolated the problem. It will take a re-write of the handling of the SD card file names. This is required to free up some additional memory. I was using a shared buffer for all 4 drives. This doesn't work with some programs as they expect repeat block reads to be immediate. So, I will need 4 x 1k buffers. One for each drive. The additional benefit will be an increase in the number of files and the length of the file names that can be used. 

It will take a few days to re-write the SD card file name display section and setup the additional buffers.

**Comment by JohnLundy** [comment]
Yes, I did see in the serial monitor that it choked on the second read of block 4. I also discovered that Buck Rogers locks up on block 28 when it starts to load the second screen. It also happens on the original beta (single drive) as well.

**Comment by Kalidomra** [comment]
My latest builds load Buck Rogers fine and plays through a few levels. Unfortunately, I'm not very good at it. I did not change the main read routine very much. Can you send me the image you tried, so I can check it.

**Comment by JohnLundy** [comment]
Buck Rogers problem solved. Over the last couple days I switched from mirco SD to SD and used an older card with game images and apparently Buck Rogers was corrupt. Sorry for the confusion.

**Comment by Kalidomra** [comment]
Fixed in v0.3
